#!/usr/bin/env python3
"""
Export utilities for Smart To-Do List
Supports Markdown (Structured PRD) and Plain Text formats
"""

import os
from datetime import datetime

class PRDExporter:
    @staticmethod
    def generate_markdown(tasks):
        """Generates a structured Markdown PRD document"""
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        md = f"# Product Requirements Document (PRD)\n"
        md += f"*Generated by Smart To-Do List on {now}*\n\n"
        md += "---\n\n"

        # Group tasks by category
        categories = {}
        for task in tasks:
            cat = task.category if task.category else "General Requirements"
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(task)

        for cat, cat_tasks in categories.items():
            md += f"## {cat}\n\n"
            for task in cat_tasks:
                status_icon = "✅" if task.status.value == "completed" else "⏳"
                priority_icon = task.priority.get_emoji()
                md += f"### {status_icon} {task.title} {priority_icon}\n"
                
                if task.description:
                    md += f"\n**Description:**\n{task.description}\n"
                
                if task.checklist:
                    md += "\n**Checklist:**\n"
                    for item in task.checklist:
                        check = "[x]" if item.completed else "[ ]"
                        md += f"- {check} {item.text}\n"
                
                md += f"\n*Status: {task.status.to_string()} | Priority: {task.priority.to_string()}*\n"
                md += "\n---\n\n"
        
        return md

    @staticmethod
    def generate_text(tasks):
        """Generates a simple plain text report"""
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        txt = f"PROJECT STATUS REPORT - {now}\n"
        txt += "="*40 + "\n\n"

        for task in tasks:
            status = "[DONE]" if task.status.value == "completed" else "[TODO]"
            txt += f"{status} {task.title} ({task.priority.to_string()})\n"
            if task.category:
                txt += f"Section: {task.category}\n"
            if task.description:
                txt += f"Description: {task.description}\n"
            if task.checklist:
                txt += "Checklist:\n"
                for item in task.checklist:
                    c = "v" if item.completed else " "
                    txt += f"  [{c}] {item.text}\n"
            txt += "-"*20 + "\n"
        
        return txt
